/**
 * ═══════════════════════════════════════════════════════════════
 * KAPITEL 06 — DUNKELKAMMER
 * Guest character: ASP-1024 — the silent legend who solved
 *   Kalibrierungsanlage I first, before anyone. Barely speaks; writes
 *   only four short sentences. A master of hiding codes inside pictures.
 *
 * Retrofitted onto GameEngine.chapter: the shared chrome (sys-bar, title
 * card, scene, choices, hint bar, complete) is generated by the scaffold;
 * only the BILDFORENSIK puzzle + narrative live here.
 *
 * Difficulty target: ~8.25 (resist the decoy + precise threshold reading)
 * ═══════════════════════════════════════════════════════════════
 */

const Chapter6 = (() => {
  'use strict';

  const CH = GameEngine.chapter;

  const S = {
    choice1Seen: { who:false, what:false, hide:false },
    hotspots: { plate:0, shelf:0, log:0, r3mi:0, vtgm:0, guest:0 },
    sigFound: false,
    solved: false,
  };

  function playSound(src){ try { const a = new Audio(`audio/${src}`); a.play(); } catch(_) {} }

  // ─── BUILD ────────────────────────────────────────────────────
  function buildChapter() {
    CH.build({
      title: 'KA-II // Kapitel 6 — Dunkelkammer',
      num: '06',
      sector: 'DUNKELKAMMER',
      reactPct: 52,
      name: 'Dunkelkammer',
      subline: '„Was versteckt ist, bleibt.“',
      emblemDeco: '<div class="ch-eye"></div>',
      scene: { img: 'cg/ch6_darkroom.png', ph: 'dark-dim' },
      guest: { key: 'asp', name: 'ASP-1024' },
      modals: ['stegModal'],
      completeId: 'ch6',
      completeAch: 'ch6_complete',
      next: { title: 'SEKTOR 07 FREIGEGEBEN', label: 'NÄCHSTER SEKTOR',
              href: '../chapter7/chapter7.html', enter: 'EINTRETEN' },
      onStart: scene_6_1_arrival,
      onRobot: clickRobot,
    });
  }

  // ─── SCENE 6.1 — ARRIVAL ──────────────────────────────────────
  function scene_6_1_arrival() {
    CH.setScene('dark-dim', 'cg/ch6_darkroom.png');
    CH.clearHotspots();
    CH.showRobots(true);
    CH.showGuest(false);
    GameEngine.dialogue.load([
      { speaker:'SYSTEM', text:'SEKTOR 06 — DUNKELKAMMER. Reihen von Bildschirmen, alle dunkel. An Leinen hängen alte Aufnahmen, lichtdicht verhängt. Es riecht nach Chemie und Geduld.' },
      { speaker:'R-3MI',  text:'„Oh. Hier wohnt der Stille."' },
      { speaker:'V-TGM',  text:'"ASP-1024. He solved the first facility before anyone. Then he stopped talking."', subtitle:'ASP-1024. Er hat die erste Anlage vor allen gelöst. Dann hörte er auf zu reden.' },
      { speaker:'R-3MI',  text:'„Nicht ganz. Vier Sätze. Immer nur vier. Mehr kriegt man nicht."' },
      { speaker:'SYSTEM', text:'Im Halbdunkel sitzt eine Gestalt vollkommen reglos vor einem schwarzen Schirm. Sie hat euch längst bemerkt.' },
    ], () => scene_6_2_asp());
  }

  // ─── SCENE 6.2 — ASP-1024 APPEARS ─────────────────────────────
  function scene_6_2_asp() {
    CH.setScene('dark-lit', 'cg/ch6_asp.png');
    playSound('ch6_asp.mp3');
    GameEngine.dialogue.load([
      { speaker:'ASP-1024', text:'„Du bist spät. Ich war zuerst. Immer. Setz dich."' },
      { speaker:'R-3MI',  text:'„Das waren schon seine Begrüßung UND sein Lebenslauf."' },
      { speaker:'V-TGM',  text:'"He means it warmly. I think."', subtitle:'Er meint es herzlich. Glaube ich.' },
      { speaker:'ASP-1024', text:'„Ein Bild. Ein Code. Versteckt. Find ihn."' },
      { speaker:'R-3MI',  text:'„Vier Sätze, ein ganzes Rätsel. Effizient. Beunruhigend."' },
    ], () => scene_6_3_choice1());
  }

  // ─── SCENE 6.3 — CHOICE 1 ─────────────────────────────────────
  const C1 = {
    who: {
      key:'who', label:'[Wer bist du?]', seen:false,
      lines:[
        { speaker:'ASP-1024', text:'„ASP. Tausendvierundzwanzig. Erster in Anlage Eins. Das reicht."' },
        { speaker:'R-3MI',  text:'„»Erster in Anlage Eins«. Er sagt das, wie andere ihren Namen sagen."' },
        { speaker:'V-TGM',  text:'"Before this place, there was another. He was its first solver. The only one who finished."', subtitle:'Vor diesem Ort gab es einen anderen. Er war sein erster Löser. Der einzige, der es zu Ende brachte.' },
        { speaker:'ASP-1024', text:'„Danach wurde es still. Ich blieb. Ich höre. Ich warte."' },
      ],
    },
    what: {
      key:'what', label:'[Was machst du hier?]', seen:false,
      lines:[
        { speaker:'ASP-1024', text:'„Ich verstecke. In Bildern. Codes, Worte, Wahrheiten. Niemand findet sie."' },
        { speaker:'R-3MI',  text:'„Er hat einmal eine ganze Karte in einem Foto von einer Wand versteckt. Wir haben sie nie gefunden."' },
        { speaker:'V-TGM',  text:'"A picture has three layers of light. Most people only see one."', subtitle:'Ein Bild hat drei Lichtschichten. Die meisten sehen nur eine.' },
        { speaker:'ASP-1024', text:'„Rot. Grün. Blau. Eine lügt. Eine flüstert."' },
      ],
    },
    hide: {
      key:'hide', label:'[Warum versteckst du alles?]', seen:false,
      lines:[
        { speaker:'ASP-1024', text:'„Was offen liegt, geht verloren. Was versteckt ist, bleibt. Frag die Anlage."' },
        { speaker:'V-TGM',  text:'"He hides things so they survive being forgotten."', subtitle:'Er versteckt Dinge, damit sie das Vergessen überleben.' },
        { speaker:'R-3MI',  text:'„Das ist… eigentlich traurig schön."' },
        { speaker:'ASP-1024', text:'„Es ist nur praktisch. Sag das nicht weiter."' },
      ],
    },
  };

  function scene_6_3_choice1() {
    CH.showGuest(true);
    const choices = Object.values(C1);
    CH.showChoices({
      prompt: 'ERSTE FRAGEN — ALLE AUSWÄHLEN:',
      hint: choices.filter(c => !c.seen).length + ' AUSSTEHEND',
      choices,
      onAfterChoice: (key, cfg) => {
        S.choice1Seen[key] = true;
        if (CH.allSeen(choices)) setTimeout(() => scene_6_4_explore(), 400);
        else { cfg.hint = `NOCH ${choices.filter(c => !c.seen).length} AUSSTEHEND`; CH.showChoices(cfg); }
      },
    });
  }

  // ─── SCENE 6.4 — EXPLORATION ──────────────────────────────────
  function scene_6_4_explore() {
    GameEngine.dialogue.load([
      { speaker:'ASP-1024', text:'„Schau dich um. Oder nicht. Das Bild wartet. Ich auch."' },
      { speaker:'SYSTEM', text:'SEKTOR 06 — EIN VERSCHLUSS AKTIV: BILDFORENSIK.' },
    ], () => loadExploreHotspots());
  }

  function loadExploreHotspots() {
    CH.clearHotspots();
    CH.addHotspot({ x:48, y:46, w:13, h:16, cls:'hs-guest', label:'BELICHTETE PLATTE', fn:() => clickExplore('plate') });
    CH.addHotspot({ x:16, y:42, w:8,  h:18, label:'BILDARCHIV',  fn:() => clickExplore('shelf') });
    CH.addHotspot({ x:82, y:62, w:7,  h:10, label:'ASPS LOGBUCH', fn:() => clickExplore('log') });
  }

  function clickExplore(key) {
    S.hotspots[key]++;

    if (key === 'log') {
      if (!S.sigFound) {
        S.sigFound = true;
        GameEngine.dialogue.load([
          { speaker:'SYSTEM', text:'ASPs Logbuch. Eine einzige Seite, vier kurze Zeilen in winziger Schrift. Die letzte Zeile ist tiefer eingedrückt als die anderen — wie eine Frequenz.' },
          { speaker:'ASP-1024', text:'„Vier Sätze. Mehr braucht keiner. Lies den letzten."' },
        ], () => {
          try { GameEngine.signals.find('sig_04'); } catch(_) {}
          GameEngine.dialogue.load([
            { speaker:'V-TGM', text:'"…they are listening. both. from the start."', subtitle:'…sie hören zu. beide. seit anfang an.' },
            { speaker:'ASP-1024', text:'„Ich weiß. Ich höre sie auch. Schon lange."' },
          ]);
        });
      } else {
        GameEngine.dialogue.load([{ speaker:'ASP-1024', text:'„Vier Zeilen. Eine Wahrheit. Den Rest behalte ich."' }]);
      }
      return;
    }

    if (key === 'shelf') {
      GameEngine.dialogue.load([
        { speaker:'SYSTEM', text:'Ein Archiv voller Bilder. Auf den ersten Blick harmlos: Wände, Gänge, Türen. In jedem einzelnen, ahnst du, steckt etwas, das nur ASP sieht.' },
        { speaker:'R-3MI',  text:'„In wie vielen davon sind Codes versteckt?"' },
        { speaker:'ASP-1024', text:'„In allen. Auch in denen, die du nicht siehst. Besonders in denen."' },
      ]);
      return;
    }

    if (key === 'plate') {
      if (!S.solved) {
        GameEngine.dialogue.load([
          { speaker:'SYSTEM', text:'Eine einzelne belichtete Platte unter Glas. Sie zeigt nur körniges Rauschen — graues Flimmern, scheinbar bedeutungslos.' },
          { speaker:'ASP-1024', text:'„Da ist ein Code. Vier Zeichen. Eine Farbe trägt ihn. Find ihn."' },
        ], () => openSteg());
      } else {
        GameEngine.dialogue.load([{ speaker:'ASP-1024', text:'„Du hast ihn gesehen. Gut. Wenige tun das."' }]);
      }
      return;
    }
  }

  function clickRobot(who) {
    S.hotspots[who]++;
    const n = S.hotspots[who];
    const byWho = {
      r3mi: [
        [{ speaker:'R-3MI', text:'„Ich rede mit ihm seit Jahren. Er hat mir 36 Sätze geschenkt. Ich zähle sie."' }],
        [{ speaker:'R-3MI', text:'„Die laute Farbe ist immer die Falle. Bei ihm ist nichts laut, was wichtig ist."' }],
      ],
      vtgm: [
        [{ speaker:'V-TGM', text:'"Isolate each channel. The truth hides in the quiet one."', subtitle:'Isoliere jeden Kanal. Die Wahrheit versteckt sich im leisen.' }],
        [{ speaker:'V-TGM', text:'"Raise the threshold until noise dies and only the shape remains."', subtitle:'Erhöhe die Schwelle, bis das Rauschen stirbt und nur die Form bleibt.' }],
      ],
      guest: [
        [{ speaker:'ASP-1024', text:'„Drei Farben. Eine schreit. Ignorier sie."' }],
        [{ speaker:'ASP-1024', text:'„Blau ist leise. Heb die Schwelle. Dann lies."' }],
      ],
    };
    const arr = byWho[who] || [];
    const line = arr[Math.min(n - 1, arr.length - 1)];
    if (line) GameEngine.dialogue.load(line);
  }

  // ═══════════════════════════════════════════════════════════════
  // BILDFORENSIK — four letters, four hiding places
  // ═══════════════════════════════════════════════════════════════
  /*
   * Four letters, left to right. Each lives in ONE colour channel and is
   * transformed differently, so no single view ever shows the whole code:
   *   col 1  RED   · plain               (channel R, threshold)
   *   col 2  GREEN · inverted             (channel G, INVERT, threshold)
   *   col 3  BLUE  · upside-down          (channel B, FLIP, threshold)
   *   col 4  RED   · inverted + flipped   ("glitched": R, INVERT, FLIP, threshold)
   * A letter sits at 128±DELTA in its channel only; everywhere else is ±NOISE.
   * Under the wrong channel/invert/flip it collapses into the noise floor and
   * vanishes at threshold. Verified separable (band width ~18 at T≈140).
   */
  const STEG_W = 280, STEG_H = 110;
  const COLS = 4, COLW = STEG_W / COLS;
  const CODE_CHARS = 'ACEFHJKLNPRTXY3479';
  const NOISE = 6, DELTA = 24;

  // recipe per column: carrier channel, polarity (dark needs INVERT), orientation (flip)
  const RECIPES = [
    { ch:'r', dark:false, flip:false },
    { ch:'g', dark:true,  flip:false },
    { ch:'b', dark:false, flip:true  },
    { ch:'r', dark:true,  flip:true  },
  ];

  let ST = null; // { channel, invert, flip, threshold, R,G,B, code }

  function rnd(a){ return Math.round((Math.random()*2 - 1) * a); }
  function randChar(){ return CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)]; }

  // mask for one letter, drawn in its column, optionally vertically mirrored
  function letterMask(chr, col, flip) {
    const c = document.createElement('canvas'); c.width = STEG_W; c.height = STEG_H;
    const x = c.getContext('2d');
    x.fillStyle = '#000'; x.fillRect(0, 0, STEG_W, STEG_H);
    if (flip) { x.translate(0, STEG_H); x.scale(1, -1); }
    x.fillStyle = '#fff'; x.textAlign = 'center'; x.textBaseline = 'middle';
    x.font = `bold ${Math.floor(STEG_H * 0.6)}px "Share Tech Mono", monospace`;
    x.fillText(chr, col * COLW + COLW / 2, STEG_H / 2 + 2);
    const d = x.getImageData(0, 0, STEG_W, STEG_H).data;
    const mask = new Uint8Array(STEG_W * STEG_H);
    for (let i = 0; i < mask.length; i++) mask[i] = d[i*4] > 128 ? 1 : 0;
    return mask;
  }

  function buildImage() {
    const n = STEG_W * STEG_H;
    ST.R = new Uint8ClampedArray(n);
    ST.G = new Uint8ClampedArray(n);
    ST.B = new Uint8ClampedArray(n);
    for (let i = 0; i < n; i++) { ST.R[i] = 128 + rnd(NOISE); ST.G[i] = 128 + rnd(NOISE); ST.B[i] = 128 + rnd(NOISE); }
    const letters = [];
    RECIPES.forEach((r, col) => {
      const chr = randChar();
      letters.push(chr);
      const mask = letterMask(chr, col, r.flip);
      const arr  = r.ch === 'r' ? ST.R : r.ch === 'g' ? ST.G : ST.B;
      const val  = 128 + (r.dark ? -DELTA : DELTA);
      for (let i = 0; i < n; i++) if (mask[i]) arr[i] = val + rnd(2);
    });
    ST.code = letters.join('');
  }

  function drawCanvas() {
    const cv = document.getElementById('stegCanvas');
    if (!cv) return;
    const ctx = cv.getContext('2d');
    const img = ctx.createImageData(STEG_W, STEG_H);
    const d = img.data;
    const t = ST.threshold;
    const GRAIN = 44;
    const gr = () => Math.round((Math.random() * 2 - 1) * GRAIN);
    const clamp = v => v < 0 ? 0 : v > 255 ? 255 : v;
    for (let y = 0; y < STEG_H; y++) {
      const srcY = ST.flip ? (STEG_H - 1 - y) : y;          // FLIP mirrors the whole frame vertically
      for (let x = 0; x < STEG_W; x++) {
        const si = srcY * STEG_W + x;
        let r, g, b;
        if (ST.channel === 'rgb') {
          // The full RGB scan is deliberately useless: heavy colour grain buries
          // every channel's faint letter. You must take the channels apart.
          r = clamp(ST.R[si] + gr()); g = clamp(ST.G[si] + gr()); b = clamp(ST.B[si] + gr());
          if (ST.invert) { r = 255-r; g = 255-g; b = 255-b; }
        } else {
          let val = ST.channel === 'r' ? ST.R[si] : ST.channel === 'g' ? ST.G[si] : ST.B[si];
          if (ST.invert) val = 255 - val;
          if (t > 0) { val = val >= t ? 255 : 0; }            // clean threshold reveals the letter
          else { val = clamp(val + gr()); }                   // raw preview is buried in grain
          r = g = b = val;
        }
        const p = (y * STEG_W + x) * 4; d[p] = r; d[p+1] = g; d[p+2] = b; d[p+3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
  }

  function openSteg() {
    ST = { channel:'rgb', invert:false, flip:false, threshold:0, R:null, G:null, B:null, code:'' };
    buildImage();
    CH.initHints({
      counts: { r3mi:1, vtgm:1, guest:2 },
      names:  { guest:'ASP-1024' },
      banks: {
        r3mi: ['„Vier Buchstaben, vier Verstecke — eine Spalte pro Zeichen. Nimm dir eine vor und dreh für SIE allein an Kanal, Invert und Flip, bis genau ein Zeichen scharf wird."'],
        vtgm: [{ speaker:'V-TGM', text:'"No single view shows all four. Each letter wants its own channel, its own invert, its own flip. Read one, then change everything for the next."',
                 subtitle:'Keine Ansicht zeigt alle vier. Jeder Buchstabe will seinen eigenen Kanal, sein eigenes Invert, seinen eigenen Flip. Lies einen, dann stell für den nächsten alles um.' }],
        guest: [
          '„Vier. Jeder anders. Einer steht. Einer steht kopf. Einer kehrt sich um. Einer ist beides."',
          '„Rot. Dann Grün, invertiert. Dann Blau, gekippt. Der Letzte: Rot, invertiert UND gekippt. Schwelle hoch. Lies."',
        ],
      },
      empty: {
        r3mi:  { speaker:'R-3MI', text:'„Mehr habe ich nicht. Aber du bist nah dran."' },
        vtgm:  { speaker:'V-TGM', text:'"That is all I have."', subtitle:'Mehr habe ich nicht.' },
        guest: { speaker:'ASP-1024', text:'„Genug. Der Rest ist deiner."' },
      },
    });
    GameEngine.dialogue.load([
      { speaker:'SYSTEM', text:'BILDFORENSIK // KANAL · INVERT · FLIP · SCHWELLE.' },
      { speaker:'ASP-1024', text:'„Das ganze Bild ist nur Rauschen. Nimm einen Kanal. Heb die Schwelle, bis EIN Zeichen aus dem Grau tritt. Vier Spalten, vier Wege."' },
    ], () => {
      document.getElementById('stegModal').classList.remove('hidden');
      const inp = document.getElementById('stegInput'); if (inp) inp.value = '';
      syncStegUI();
      drawCanvas();
      setStegStatus('Das volle Bild ist nur Statik. Nimm die Kanäle einzeln — und heb die Schwelle.', '');
    });
  }

  function syncStegUI() {
    document.querySelectorAll('#stegChannels .steg-ch').forEach(b =>
      b.classList.toggle('active', b.dataset.ch === ST.channel));
    const inv = document.getElementById('stegInvertBtn');
    if (inv) inv.classList.toggle('active', ST.invert);
    const fl = document.getElementById('stegFlipBtn');
    if (fl) fl.classList.toggle('active', ST.flip);
    const sl = document.getElementById('stegThreshold');
    if (sl) sl.value = ST.threshold;
    const lbl = document.getElementById('stegThreshLabel');
    if (lbl) lbl.textContent = ST.threshold === 0 ? 'AUS' : ST.threshold;
  }

  function stegChannel(c) { if (!ST) return; ST.channel = c; syncStegUI(); drawCanvas(); }
  function stegInvert()   { if (!ST) return; ST.invert = !ST.invert; syncStegUI(); drawCanvas(); }
  function stegFlip()     { if (!ST) return; ST.flip = !ST.flip; syncStegUI(); drawCanvas(); }
  function stegThreshold(v){ if (!ST) return; ST.threshold = parseInt(v, 10) || 0; syncStegUI(); drawCanvas(); }
  function stegReset() {
    if (!ST) return;
    ST.channel = 'rgb'; ST.invert = false; ST.flip = false; ST.threshold = 0;
    syncStegUI(); drawCanvas(); setStegStatus('Ansicht zurückgesetzt.', '');
  }

  function stegSubmit() {
    if (!ST || S.solved) return;
    const raw = (document.getElementById('stegInput').value || '').trim().toUpperCase();
    if (raw.length < 4) { setStegStatus('Vier Zeichen. Nicht weniger.', 'warn'); return; }
    if (raw === ST.code) {
      S.solved = true;
      setStegStatus('CODE BESTÄTIGT.', 'ok');
      playSound('ch6_ok.mp3');
      try { GameEngine.audio.solve(); } catch(_) {}
      setTimeout(() => solveSteg(), 900);
    } else {
      const hits = [...raw].filter((c, i) => c === ST.code[i]).length;
      setStegStatus(hits >= 2
        ? `${hits} von 4 stehen. Die anderen liest du falsch herum — Spalte für Spalte.`
        : 'Nein. Jede Spalte braucht ihre eigene Ansicht. Eins steht, eins steht kopf.', 'error');
      try { GameEngine.audio.fail(); } catch(_) {}
    }
  }

  function setStegStatus(text, type) {
    const el = document.getElementById('stegStatus');
    el.textContent = text; el.className = 'puzzle-status sys-text' + (type ? ' ' + type : '');
  }

  function solveSteg() {
    document.getElementById('stegModal').classList.add('hidden');
    CH.showHintBar(false);
    CH.setProgress(64);
    GameEngine.dialogue.load([
      { speaker:'SYSTEM', text:'VERBORGENER CODE EXTRAHIERT. DUNKELKAMMER ENTRIEGELT.' },
      { speaker:'ASP-1024', text:'„Du hast es gesehen. Das Leise. Wenige können das. Gut."' },
      { speaker:'R-3MI',  text:'„Das waren VIER Sätze des Lobes. Ich glaube, das ist ein Rekord."' },
      { speaker:'V-TGM',  text:'"He just gave you something he gives almost no one."', subtitle:'Er hat dir gerade etwas gegeben, das er fast niemandem gibt.' },
      { speaker:'ASP-1024', text:'„Geh weiter. Sektor sieben. Pass auf. Sie hören zu."' },
      { speaker:'V-TGM',  text:'"Sektor 07 is open."', subtitle:'Sektor 07 ist offen.' },
    ], () => CH.complete());
  }

  // ─── PUBLIC API ───────────────────────────────────────────────
  function init() {
    buildChapter();
    CH.start();
  }

  return {
    init,
    stegChannel,
    stegInvert,
    stegFlip,
    stegThreshold,
    stegReset,
    stegSubmit,
  };

})();

document.addEventListener('DOMContentLoaded', () => Chapter6.init());
