/**
 * ═══════════════════════════════════════════════════════════════
 * KAPITEL 05 — FÖRDERSEKTOR
 * Guest character: T-FLON14 (Teflon) — warm but relentless coach;
 *   frictionless, fast, runs the facility's long "power trail" of
 *   quick locks. "Komm, weiter, nicht stehenbleiben — du schaffst das!"
 *
 * Retrofitted onto GameEngine.chapter: shared chrome is generated by the
 * scaffold; only the FÖRDERLAUF minigame + narrative live here. The hint
 * pauses the clock via the scaffold's onHintOpen/onHintClose hooks.
 *
 * Difficulty target: ~7.5 (speed + escalating subtlety)
 * Tuning knobs: FL_TIME (clock), FL_PENALTY (wrong-tap cost), ROUNDS.
 * ═══════════════════════════════════════════════════════════════
 */

const Chapter5 = (() => {
  'use strict';

  const CH = GameEngine.chapter;

  const S = {
    choice1Seen: { who:false, what:false, fast:false },
    hotspots: { band:0, marker:0, sign:0, r3mi:0, vtgm:0, guest:0 },
    sigFound: false,
    solved: false,
  };

  function playSound(src){ try { const a = new Audio(`audio/${src}`); a.play(); } catch(_) {} }

  // ─── BUILD ────────────────────────────────────────────────────
  function buildChapter() {
    CH.build({
      title: 'KA-II // Kapitel 5 — Fördersektor',
      num: '05',
      sector: 'FÖRDERSEKTOR',
      reactPct: 40,
      name: 'Fördersektor',
      subline: '„Stehen ist nur langsames Umfallen.“',
      emblemDeco: '<div class="ch5-dash"></div>',
      scene: { img: 'cg/ch5_trail.png', ph: 'trail-dim' },
      guest: { key: 'tflon', name: 'T-FLON14' },
      modals: ['flModal'],
      completeId: 'ch5',
      completeAch: 'ch5_complete',
      next: { title: 'SEKTOR 06 FREIGEGEBEN', label: 'DUNKELKAMMER',
              href: '../chapter6/chapter6.html', enter: 'EINTRETEN' },
      onStart: scene_5_1_arrival,
      onRobot: clickRobot,
    });
  }

  // ─── SCENE 5.1 — ARRIVAL ──────────────────────────────────────
  function scene_5_1_arrival() {
    CH.setScene('trail-dim', 'cg/ch5_trail.png');
    CH.clearHotspots();
    CH.showRobots(true);
    CH.showGuest(false);
    GameEngine.dialogue.load([
      { speaker:'SYSTEM', text:'SEKTOR 05 — FÖRDERSEKTOR. Ein endlos langer Gang. Förderbänder laufen leer in beide Richtungen. An den Wänden: hunderte kleine Verschlüsse, einer nach dem anderen, so weit man sehen kann.' },
      { speaker:'R-3MI',  text:'„Das sind… sehr viele Schlösser."' },
      { speaker:'V-TGM',  text:'"Hundreds. Small ones. Fast ones."', subtitle:'Hunderte. Kleine. Schnelle.' },
      { speaker:'SYSTEM', text:'Etwas gleitet heran. Schnell. Geräuschlos. Es bremst erst im allerletzten Moment — und rutscht dann trotzdem noch ein Stück weiter.' },
      { speaker:'T-FLON14', text:'„Oh! Frischfleisch! Äh — ich meine: ein neues Gesicht! Willkommen, willkommen, nicht stehenbleiben, komm, komm!"' },
    ], () => scene_5_2_tflon());
  }

  // ─── SCENE 5.2 — T-FLON14 APPEARS ─────────────────────────────
  function scene_5_2_tflon() {
    CH.setScene('trail-lit', 'cg/ch5_tflon.png');
    playSound('ch5_tflon.mp3');
    GameEngine.dialogue.load([
      { speaker:'T-FLON14', text:'„T-FLON14. Aber sag T-FLON, das spart Zeit, und Zeit ist hier alles. Ich halte diesen Sektor in Bewegung. Buchstäblich."' },
      { speaker:'T-FLON14', text:'„An mir bleibt nichts haften. Kein Dreck, keine Sorgen, keine schlechte Laune. Ich rutsche einfach weiter. Das solltest du auch lernen."' },
      { speaker:'R-3MI',  text:'„Sie ist… anstrengend positiv."' },
      { speaker:'T-FLON14', text:'„Das ist ein Kompliment, ich nehme es! Also: Dieser Sektor ist eine Strecke. Viele kleine Aufgaben, schnell hintereinander. Power-Lauf nennt man das."' },
      { speaker:'V-TGM',  text:'"She is the fastest unit here."', subtitle:'Sie ist die schnellste Einheit hier.' },
      { speaker:'T-FLON14', text:'„Die schnellste, ja! Und heute machst du mit. Keine Angst — ich bring dich da durch. Tempo, Köpfchen, und nicht hängenbleiben. Auf geht\'s!"' },
    ], () => scene_5_3_choice1());
  }

  // ─── SCENE 5.3 — CHOICE 1 ─────────────────────────────────────
  const C1 = {
    who: {
      key:'who', label:'[Wer bist du, T-FLON?]', seen:false,
      lines:[
        { speaker:'T-FLON14', text:'„Die Fördereinheit. Ich bring Dinge von A nach B, und zwar schnell. Pakete, Daten, Testpersonen — alles, was sich bewegen lässt."' },
        { speaker:'R-3MI',  text:'„Sie hat mich mal von einem Sektor in den nächsten »gefördert«. Ohne zu fragen."' },
        { speaker:'T-FLON14', text:'„Du warst im Weg und hast geredet. Zwei Probleme, eine Lösung!"' },
        { speaker:'V-TGM',  text:'"She is not unkind. Just… directional."', subtitle:'Sie ist nicht unfreundlich. Nur… zielgerichtet.' },
      ],
    },
    what: {
      key:'what', label:'[Was ist dieser Sektor?]', seen:false,
      lines:[
        { speaker:'T-FLON14', text:'„Die Strecke! Hunderte winzige Schlösser, alle leicht — einzeln. Der Trick ist die Menge und das Tempo."' },
        { speaker:'T-FLON14', text:'„Die Anlage hat hier früher alles im Akkord geprüft. Schnell, schneller, weiter. Ich hab den Rhythmus nie verloren."' },
        { speaker:'R-3MI',  text:'„Sie ist wortwörtlich nie stehengeblieben."' },
        { speaker:'T-FLON14', text:'„Wozu auch? Stehen ist nur langsames Umfallen."' },
      ],
    },
    fast: {
      key:'fast', label:'[Warum so eilig?]', seen:false,
      lines:[
        { speaker:'T-FLON14', text:'„Eilig? Nein. Effizient. Wenn du einmal stehenbleibst, merkst du, wie still es hier ist. Und wie lange schon."' },
        { speaker:'T-FLON14', text:'„Also bleib ich in Bewegung. Solange ich laufe, ist die Anlage nicht ganz tot. Verstehst du?"' },
        { speaker:'V-TGM',  text:'"That is the saddest fast thing I have heard."', subtitle:'Das ist das traurigste schnelle Ding, das ich je gehört habe.' },
        { speaker:'T-FLON14', text:'„Pssst! Nicht traurig. Schwungvoll! Komm, weiter."' },
      ],
    },
  };

  function scene_5_3_choice1() {
    CH.showGuest(true);
    const choices = Object.values(C1);
    CH.showChoices({
      prompt: 'ERSTE FRAGEN — ALLE AUSWÄHLEN:',
      hint: choices.filter(c => !c.seen).length + ' AUSSTEHEND',
      choices,
      onAfterChoice: (key, cfg) => {
        S.choice1Seen[key] = true;
        if (CH.allSeen(choices)) setTimeout(() => scene_5_4_explore(), 400);
        else { cfg.hint = `NOCH ${choices.filter(c => !c.seen).length} AUSSTEHEND`; CH.showChoices(cfg); }
      },
    });
  }

  // ─── SCENE 5.4 — EXPLORATION ──────────────────────────────────
  function scene_5_4_explore() {
    GameEngine.dialogue.load([
      { speaker:'T-FLON14', text:'„Schau dich kurz um — aber wirklich nur kurz. Dann laufen wir. Die Strecke wartet nicht ewig auf gut gelaunt."' },
      { speaker:'SYSTEM', text:'SEKTOR 05 — FÖRDERLAUF BEREIT. 20 PRÜFUNGEN. EINE UHR.' },
    ], () => loadExploreHotspots());
  }

  function loadExploreHotspots() {
    CH.clearHotspots();
    CH.addHotspot({ x:48, y:50, w:14, h:16, cls:'hs-guest', label:'STARTLINIE', fn:() => clickExplore('band') });
    CH.addHotspot({ x:18, y:44, w:7,  h:14, label:'STRECKENMARKER', fn:() => clickExplore('marker') });
    CH.addHotspot({ x:82, y:60, w:7,  h:12, label:'ALTE ANZEIGETAFEL', fn:() => clickExplore('sign') });
  }

  function clickExplore(key) {
    S.hotspots[key]++;

    if (key === 'marker') {
      if (!S.sigFound) {
        S.sigFound = true;
        GameEngine.dialogue.load([
          { speaker:'SYSTEM', text:'Ein Streckenmarker, schief in der Wand. Die eingestanzten Zahlen darauf ergeben keinen Sinn — sie stimmen mit keiner Karte überein. Dahinter, schwach: ein Sender.' },
          { speaker:'T-FLON14', text:'„Den Marker mag ich nicht. Seine Zahlen waren nie richtig. Ich laufe da immer ein bisschen schneller vorbei."' },
        ], () => {
          try { GameEngine.signals.find('sig_03'); } catch(_) {}
          GameEngine.dialogue.load([
            { speaker:'V-TGM', text:'"…the numbers do not match the map. please correct. please."', subtitle:'…die Zahlen stimmen nicht mit der Karte überein. bitte korrigieren. bitte.' },
            { speaker:'T-FLON14', text:'„…»bitte«. Zweimal. Das gefällt mir gar nicht. Komm, weiter, bevor es noch dreimal sagt."' },
          ]);
        });
      } else {
        GameEngine.dialogue.load([{ speaker:'T-FLON14', text:'„Der schiefe Marker mit den falschen Zahlen. Lass ihn. Manche Dinge laufen besser, wenn man nicht hinschaut."' }]);
      }
      return;
    }

    if (key === 'sign') {
      GameEngine.dialogue.load([
        { speaker:'SYSTEM', text:'Eine alte Anzeigetafel über dem Band. Sie zeigt eine Bestzeit und einen Namen: T-FLON14. Darunter, viel kleiner: »Letzter Lauf vor 2.847 Tagen.«' },
        { speaker:'T-FLON14', text:'„Mein Rekord. Steht immer noch. Es war ja auch niemand mehr da, der ihn brechen könnte."' },
        { speaker:'R-3MI',  text:'„Das ist dieselbe Zahl wie am Eingang. 2.847 Tage."' },
        { speaker:'V-TGM',  text:'"Everything stopped on the same day."', subtitle:'Alles hörte am selben Tag auf.' },
      ]);
      return;
    }

    if (key === 'band') {
      if (!S.solved) {
        GameEngine.dialogue.load([
          { speaker:'SYSTEM', text:'Die Startlinie des Förderlaufs. Über dir zählt eine Uhr lautlos herunter, sobald du beginnst.' },
          { speaker:'T-FLON14', text:'„So läuft\'s: zwanzig kleine Aufgaben, eine nach der anderen, und eine einzige Uhr für alle. Falsch getippt kostet Zeit. Lies die Ansage, tipp richtig, weiter!"' },
        ], () => openFL());
      } else {
        GameEngine.dialogue.load([{ speaker:'T-FLON14', text:'„Geschafft! Und schnell warst du auch. Fast schon T-FLON-Niveau. Fast."' }]);
      }
      return;
    }
  }

  function clickRobot(who) {
    S.hotspots[who]++;
    const n = S.hotspots[who];
    const byWho = {
      r3mi: [
        [{ speaker:'R-3MI', text:'„Sie ist nett. Sie ist nur nett mit 40 km/h. Das ist gewöhnungsbedürftig."' }],
        [{ speaker:'R-3MI', text:'„Wenn sie »kurz« sagt, meint sie »jetzt sofort und schon vorbei«."' }],
      ],
      vtgm: [
        [{ speaker:'V-TGM', text:'"Keep your eyes moving, not your nerves."', subtitle:'Lass die Augen wandern, nicht die Nerven.' }],
        [{ speaker:'V-TGM', text:'"She runs so she does not have to stop and listen to the silence."', subtitle:'Sie läuft, um nicht stehen zu bleiben und der Stille zuzuhören.' }],
      ],
      guest: [
        [{ speaker:'T-FLON14', text:'„Brauchst du was? Mach schnell — nein, Spaß. Naja. Halber Spaß."' }],
        [{ speaker:'T-FLON14', text:'„Du machst das gut! Doch, wirklich! Ich sag das nicht zu jedem. Nur zu fast jedem. Komm, weiter!"' }],
      ],
    };
    const arr = byWho[who] || [];
    const line = arr[Math.min(n - 1, arr.length - 1)];
    if (line) GameEngine.dialogue.load(line);
  }

  // ═══════════════════════════════════════════════════════════════
  // FÖRDERLAUF — 20 rapid mixed micro-tasks under one global clock
  // ═══════════════════════════════════════════════════════════════
  const ROUNDS    = 20;
  const FL_TIME   = 60;   // seconds on the clock (tunable — lower = meaner)
  const FL_PENALTY = 3;   // seconds lost per wrong tap
  const TICK      = 100;

  // filled/outline pairs — "hard" rounds mix a target with its look-alike twin
  const PAIRS   = [['●','○'],['■','□'],['▲','△'],['◆','◇'],['★','☆']];
  const FILLED  = ['●','■','▲','◆','★'];
  const PALETTE = ['#e0c64a','#7fd14f','#d9534f','#3a8fd4','#c45ad9','#e6e6e6']; // always clearly distinct
  function partnerOf(g){ for (const p of PAIRS) { if (p[0]===g) return p[1]; if (p[1]===g) return p[0]; } return g; }

  let FL = null;          // { round, time, timerId, cur, found, running }
  let _flPaused = false;  // captured running-state while a hint is open

  function pick(a){ return a[Math.floor(Math.random()*a.length)]; }
  function randint(lo,hi){ return lo + Math.floor(Math.random()*(hi-lo+1)); }
  function shuffle(a){ for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
  function gridN(round){ return round<=7 ? 3 : round<=14 ? 4 : 5; }

  function makeRound(round) {
    const n = gridN(round), total = n*n;
    const hard = round > 10;
    const type = ['odd_glyph','match','tap_all','count','odd_color'][(round-1) % 5];
    const base = '#e0c64a';
    const cells = Array.from({length: total}, () => ({ glyph:'●', color:base }));

    if (type === 'odd_glyph') {
      let g, g2;
      if (hard) { const p = pick(PAIRS); g = p[0]; g2 = p[1]; }          // filled vs its outline twin
      else { g = pick(FILLED); do { g2 = pick(FILLED); } while (g2 === g); } // two clearly different shapes
      cells.forEach(c => { c.glyph = g; });
      const idx = randint(0, total-1); cells[idx].glyph = g2;
      return { type, prompt:'Finde das andere Symbol!', cells, correct:idx };
    }

    if (type === 'odd_color') {
      const glyph = pick(FILLED);
      const cs = shuffle([...PALETTE]); const cA = cs[0], cB = cs[1];     // always clearly distinct
      cells.forEach(c => { c.glyph = glyph; c.color = cA; });
      const idx = randint(0, total-1); cells[idx].color = cB;
      return { type, prompt:'Finde die andere Farbe!', cells, correct:idx };
    }

    // match / tap_all / count share distractor logic:
    // hard rounds fill the grid with the target's look-alike twin (similar, still distinct).
    const target = pick(FILLED);
    const distract = hard ? [partnerOf(target)] : FILLED.filter(g => g !== target);

    if (type === 'match') {
      cells.forEach(c => { c.glyph = pick(distract); });
      const idx = randint(0, total-1); cells[idx].glyph = target;
      return { type, prompt:'Finde dieses Symbol:', target, cells, correct:idx };
    }

    if (type === 'tap_all') {
      const k = round<=7 ? 2 : round<=14 ? 3 : 4;
      cells.forEach(c => { c.glyph = pick(distract); });
      const idxs = shuffle(Array.from({length: total}, (_,i)=>i)).slice(0, k);
      idxs.forEach(i => { cells[i].glyph = target; });
      return { type, prompt:`Tippe alle „${target}" (${k})!`, target, cells, targets:new Set(idxs) };
    }

    // count
    const maxK = total <= 9 ? 5 : total <= 16 ? 7 : 9;
    const k = randint(2, maxK);
    cells.forEach(c => { c.glyph = pick(distract); });
    shuffle(Array.from({length: total}, (_,i)=>i)).slice(0, k).forEach(i => { cells[i].glyph = target; });
    const opts = new Set([k]);
    while (opts.size < 4) opts.add(Math.max(1, k + randint(-2, 2)));
    return { type:'count', prompt:`Wie viele „${target}"?`, target, cells, answer:k, options:shuffle([...opts]) };
  }

  function openFL() {
    FL = { round:1, time:FL_TIME, timerId:null, cur:null, found:new Set(), running:true };
    CH.initHints({
      counts: { r3mi:1, vtgm:1, guest:2 },
      names:  { guest:'T-FLON14' },
      banks: {
        r3mi: ['„Lies immer zuerst die Ansage oben. »Andere Farbe« ist nicht dasselbe wie »anderes Symbol«. Klingt banal. Rettet Sekunden."'],
        vtgm: [{ speaker:'V-TGM', text:'"Scan in rows, top to bottom. Do not stare at the centre — the odd one is often at an edge."',
                 subtitle:'Scanne zeilenweise, von oben nach unten. Starr nicht in die Mitte — der Ausreißer sitzt oft am Rand.' }],
        guest: [
          '„Nicht verkrampfen! Locker bleiben, Blick weich machen, dann springt dir das Falsche von selbst ins Auge. Vertrau mir, ich mach das den ganzen Tag!"',
          '„Beim Zählen: tipp die Zahl, die sich richtig anfühlt, und lauf weiter. Grübeln kostet mehr Zeit als ein falscher Tipp. Tempo!"',
        ],
      },
      empty: {
        r3mi:  { speaker:'R-3MI', text:'„Mehr habe ich nicht. Aber du brauchst es nicht."' },
        vtgm:  { speaker:'V-TGM', text:'"That is all I have."', subtitle:'Mehr habe ich nicht.' },
        guest: { speaker:'T-FLON14', text:'„Keine Tipps mehr! Nur noch Tempo! Los los los — liebevoll gemeint!"' },
      },
      onHintOpen:  () => { _flPaused = !!(FL && FL.running); if (_flPaused) FL.running = false; },
      onHintClose: () => { if (FL && !S.solved && _flPaused) FL.running = true; },
    });
    document.getElementById('flModal').classList.remove('hidden');
    nextRound(true);
    startTimer();
  }

  function startTimer() {
    stopTimer();
    FL.timerId = setInterval(() => {
      if (!FL || !FL.running) return;
      FL.time -= TICK/1000;
      if (FL.time <= 0) { FL.time = 0; paintTimer(); return flTimeout(); }
      paintTimer();
    }, TICK);
  }
  function stopTimer() { if (FL && FL.timerId) { clearInterval(FL.timerId); FL.timerId = null; } }

  function paintTimer() {
    const pct = Math.max(0, Math.min(100, (FL.time / FL_TIME) * 100));
    const fill = document.getElementById('flTimer');
    fill.style.width = pct + '%';
    fill.classList.toggle('low', FL.time < FL_TIME * 0.25);
    document.getElementById('flTimeLabel').textContent = Math.ceil(FL.time) + 's';
  }

  function nextRound(first) {
    FL.found = new Set();
    FL.cur = makeRound(FL.round);
    document.getElementById('flProgress').textContent = `RUNDE ${FL.round} / ${ROUNDS}`;
    document.getElementById('flPrompt').innerHTML = FL.cur.prompt +
      (FL.cur.target && (FL.cur.type === 'match') ? ` <span class="fl-target">${FL.cur.target}</span>` : '');
    renderFL();
    if (!first) playSound('ch5_tick.mp3');
    paintTimer();
  }

  function renderFL() {
    const r = FL.cur;
    const n = Math.sqrt(r.cells.length);
    const grid = document.getElementById('flGrid');
    grid.style.setProperty('--cols', n);
    grid.innerHTML = '';
    r.cells.forEach((cell, i) => {
      const el = document.createElement('button');
      el.className = 'fl-cell' + (FL.found.has(i) ? ' got' : '');
      el.textContent = cell.glyph;
      el.style.color = cell.color;
      el.addEventListener('click', () => flTap(i));
      grid.appendChild(el);
    });
    // answer buttons (count only)
    const ans = document.getElementById('flAnswers');
    if (r.type === 'count') {
      ans.classList.remove('hidden');
      ans.innerHTML = '';
      r.options.forEach(o => {
        const b = document.createElement('button');
        b.className = 'ka-btn small fl-ans'; b.textContent = o;
        b.addEventListener('click', () => flAnswer(o));
        ans.appendChild(b);
      });
    } else {
      ans.classList.add('hidden'); ans.innerHTML = '';
    }
  }

  function flWrong() {
    if (!FL || !FL.running) return;
    FL.time = Math.max(0, FL.time - FL_PENALTY);
    paintTimer();
    setFLStatus(`DANEBEN! −${FL_PENALTY}s`, 'error');
    try { GameEngine.audio.fail(); } catch(_) {}
    const card = document.getElementById('flCard');
    card.classList.add('shake'); setTimeout(() => card.classList.remove('shake'), 300);
    if (FL.time <= 0) flTimeout();
  }

  function flRoundWin() {
    FL.round++;
    setFLStatus('WEITER!', 'ok');
    if (FL.round > ROUNDS) return flSolve();
    nextRound(false);
  }

  function flTap(i) {
    if (!FL || !FL.running) return;
    const r = FL.cur;
    if (r.type === 'count') return; // answered via buttons
    if (r.type === 'tap_all') {
      if (r.targets.has(i)) {
        if (!FL.found.has(i)) {
          FL.found.add(i);
          renderFL();
          if (FL.found.size === r.targets.size) flRoundWin();
        }
      } else { flWrong(); }
      return;
    }
    // odd_glyph / odd_color / match → single correct cell
    if (i === r.correct) flRoundWin(); else flWrong();
  }

  function flAnswer(val) {
    if (!FL || !FL.running || !FL.cur || FL.cur.type !== 'count') return;
    if (val === FL.cur.answer) flRoundWin(); else flWrong();
  }

  function flTimeout() {
    FL.running = false;
    stopTimer();
    setFLStatus('ZEIT ABGELAUFEN — DIE STRECKE WARTET NICHT.', 'error');
    document.getElementById('flRestart').classList.remove('hidden');
  }

  function flRestart() {
    document.getElementById('flRestart').classList.add('hidden');
    FL.round = 1; FL.time = FL_TIME; FL.running = true; FL.found = new Set();
    setFLStatus('', '');
    nextRound(true);
    startTimer();
  }

  function setFLStatus(text, type) {
    const el = document.getElementById('flStatus');
    el.textContent = text; el.className = 'puzzle-status sys-text' + (type ? ' ' + type : '');
  }

  function flSolve() {
    S.solved = true;
    FL.running = false;
    stopTimer();
    document.getElementById('flModal').classList.add('hidden');
    CH.showHintBar(false);
    CH.setProgress(52);
    playSound('ch5_finish.mp3');
    try { GameEngine.audio.solve(); } catch(_) {}
    GameEngine.dialogue.load([
      { speaker:'SYSTEM', text:'FÖRDERLAUF ABGESCHLOSSEN. ALLE 20 PRÜFUNGEN BESTANDEN. STRECKE REAKTIVIERT.' },
      { speaker:'T-FLON14', text:'„HA! Hast du gesehen?! Das war schnell! Das war richtig schnell! Ich krieg ja fast Gänsehaut, und ich hab nicht mal Haut!"' },
      { speaker:'R-3MI',  text:'„Sie ist gerührt. Auf 40 km/h."' },
      { speaker:'T-FLON14', text:'„Weißt du was? Du bleibst nicht stehen, wenn\'s drauf ankommt. Das mag ich. Das ist selten."' },
      { speaker:'T-FLON14', text:'„Die Bänder laufen wieder. Hörst du das? Das ist der schönste Lärm der Welt."' },
      { speaker:'V-TGM',  text:'"Sektor 06 is open."', subtitle:'Sektor 06 ist offen.' },
      { speaker:'T-FLON14', text:'„Geh weiter, immer weiter. Und wenn du je stehenbleiben musst — bleib wenigstens bei jemand Netten stehen."' },
    ], () => CH.complete());
  }

  // ─── PUBLIC API ───────────────────────────────────────────────
  function init() {
    buildChapter();
    CH.start();
  }

  return {
    init,
    flRestart,
  };

})();

document.addEventListener('DOMContentLoaded', () => Chapter5.init());
